name: Java CI

on:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build with Gradle
      run: ./gradlew publishPlugin -Dversion=${GITHUB_REF##*/}
      env:
        JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
      
